package DeskMusicStudio;

import jaco.mp3.player.MP3Player;
import org.jfugue.player.Player;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Scanner;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.Line;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.Mixer;
import javax.swing.*;
import javax.swing.JSlider;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileFilter;

/**
 * @author adrian & christian 
 **/
// Piano, Guitar, Violin, Banjo
public class deskMusicStudio extends javax.swing.JFrame {

    // defining jar file class
    MP3Player user;
    // defining file for track
    File songFile;
    // defining current command line directories
    String currentDirectory = "home.user";
    // application class is created 
    String currentPath;
    // defining string variable for image name
    String imagePath;
    // defining string variable for application name 
    String applicationName = "Desk Music Studio";
    //defining jar file class
    Player player = new Player();

    
    JLayeredPane panel = new JLayeredPane();
    
    String noteV;
    // if statement is false, button interaction will not repeat
    boolean repeat = false;
    
    // boolean for windowCollasped
    boolean windowCollasped = false;
    
    // creating two integers for mouse x and y depending on position on display
    int xM, yM;
   
    
    public deskMusicStudio() {
        initComponents();
        
        instrumentButtons.add(guitarButton);
        instrumentButtons.add(pianoButton);
        instrumentButtons.add(violinButton);
        instrumentButtons.add(banjoButton);
        
        // declaring application title
        apptitle.setText(applicationName);
        
        // calling for song file
        songFile = new File("/Users/adrian/Downloads/ ");
        
        
        // declare string for file name
        String fileName = songFile.getName();
        songNameDisplay.setText(fileName);
        
        
        // playmusic method
        user = mp3Player();
        // loading song to track view
        user.addToPlayList(songFile);
        
        // current path in terms of strings
        currentPath = Paths.get(".").toAbsolutePath().normalize().toString();
        imagePath = "\\images";
        
        cKey.add(panel);
        dKey.add(panel);
        eKey.add(panel);
        fKey.add(panel);
        gKey.add(panel);
        aKey.add(panel);
        bKey.add(panel);
        highCKey.add(panel);
        cSharp.add(panel);
        dSharp.add(panel);
        fSharp.add(panel);
        gSharp.add(panel);
        aSharp.add(panel);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     **/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        instrumentButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        apptitle = new javax.swing.JLabel();
        quitBtn = new javax.swing.JLabel();
        settingBtn = new javax.swing.JLabel();
        TrackViewName = new javax.swing.JLabel();
        songNameMainPanel = new javax.swing.JPanel();
        songNameSubPanel = new javax.swing.JPanel();
        songNameDisplay = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        loadBtn = new javax.swing.JLabel();
        saveBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        enterVolValue = new javax.swing.JTextField();
        enterBtn = new javax.swing.JButton();
        volSlider = new javax.swing.JSlider();
        cKey = new javax.swing.JButton();
        dKey = new javax.swing.JButton();
        eKey = new javax.swing.JButton();
        fKey = new javax.swing.JButton();
        gKey = new javax.swing.JButton();
        aKey = new javax.swing.JButton();
        cSharp = new javax.swing.JButton();
        dSharp = new javax.swing.JButton();
        fSharp = new javax.swing.JButton();
        gSharp = new javax.swing.JButton();
        bKey = new javax.swing.JButton();
        highCKey = new javax.swing.JButton();
        aSharp = new javax.swing.JButton();
        noteBanjo = new javax.swing.JLabel();
        noteGuitar = new javax.swing.JLabel();
        notePiano = new javax.swing.JLabel();
        stopBtn = new javax.swing.JButton();
        repeatBtn = new javax.swing.JButton();
        pauseBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        muteBtn = new javax.swing.JButton();
        volumeDownBtn = new javax.swing.JButton();
        volumeUpBtn = new javax.swing.JButton();
        noteViolin = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GuitarText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        PianoText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ViolinText = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        BanjoText = new javax.swing.JTextArea();
        guitarButton = new javax.swing.JRadioButton();
        pianoButton = new javax.swing.JRadioButton();
        violinButton = new javax.swing.JRadioButton();
        banjoButton = new javax.swing.JRadioButton();
        recordButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 492));

        jPanel1.setBackground(new java.awt.Color(80, 80, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(80, 80, 80));
        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 250, 250), 1, true));

        apptitle.setBackground(new java.awt.Color(102, 102, 102));
        apptitle.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        apptitle.setForeground(new java.awt.Color(102, 250, 250));
        apptitle.setText("   Desk Music Studio");
        apptitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".AppleSystemUIFont", 1, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        apptitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                apptitleMouseDragged(evt);
            }
        });
        apptitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apptitleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apptitleMousePressed(evt);
            }
        });

        quitBtn.setBackground(new java.awt.Color(102, 102, 102));
        quitBtn.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        quitBtn.setForeground(new java.awt.Color(102, 250, 250));
        quitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quitBtn.setText("Quit");
        quitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        quitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitBtnMouseClicked(evt);
            }
        });

        settingBtn.setBackground(new java.awt.Color(102, 102, 102));
        settingBtn.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        settingBtn.setForeground(new java.awt.Color(102, 250, 250));
        settingBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingBtn.setText("Settings");
        settingBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        settingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingBtnMouseClicked(evt);
            }
        });

        TrackViewName.setBackground(new java.awt.Color(102, 102, 102));
        TrackViewName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        TrackViewName.setForeground(new java.awt.Color(102, 250, 250));
        TrackViewName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TrackViewName.setText("Track View");
        TrackViewName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apptitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(687, 687, 687)
                .addComponent(TrackViewName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 701, Short.MAX_VALUE)
                .addComponent(settingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(apptitle)
                        .addComponent(settingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(TrackViewName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        apptitle.getAccessibleContext().setAccessibleName("Desk Music Studio");

        jPanel1.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        songNameMainPanel.setBackground(new java.awt.Color(50, 50, 50));

        songNameSubPanel.setBackground(new java.awt.Color(80, 80, 80));
        songNameSubPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 250, 250), 1, true));

        songNameDisplay.setBackground(new java.awt.Color(50, 50, 50));
        songNameDisplay.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        songNameDisplay.setForeground(new java.awt.Color(102, 250, 250));
        songNameDisplay.setText("Playing");
        songNameDisplay.setMaximumSize(new java.awt.Dimension(50, 16));
        songNameDisplay.setMinimumSize(new java.awt.Dimension(50, 16));

        javax.swing.GroupLayout songNameSubPanelLayout = new javax.swing.GroupLayout(songNameSubPanel);
        songNameSubPanel.setLayout(songNameSubPanelLayout);
        songNameSubPanelLayout.setHorizontalGroup(
            songNameSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(songNameSubPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(songNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1313, Short.MAX_VALUE))
        );
        songNameSubPanelLayout.setVerticalGroup(
            songNameSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(songNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout songNameMainPanelLayout = new javax.swing.GroupLayout(songNameMainPanel);
        songNameMainPanel.setLayout(songNameMainPanelLayout);
        songNameMainPanelLayout.setHorizontalGroup(
            songNameMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(songNameMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(songNameMainPanelLayout.createSequentialGroup()
                    .addComponent(songNameSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        songNameMainPanelLayout.setVerticalGroup(
            songNameMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(songNameMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(songNameMainPanelLayout.createSequentialGroup()
                    .addComponent(songNameSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(songNameMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, -1, -1));

        controlPanel.setBackground(new java.awt.Color(80, 80, 80));
        controlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 250, 250), new java.awt.Color(102, 250, 250)));
        controlPanel.setPreferredSize(new java.awt.Dimension(1920, 1040));

        loadBtn.setBackground(new java.awt.Color(102, 102, 102));
        loadBtn.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        loadBtn.setForeground(new java.awt.Color(102, 250, 250));
        loadBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadBtn.setText("Load");
        loadBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        loadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadBtnMouseClicked(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(102, 102, 102));
        saveBtn.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(102, 250, 250));
        saveBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveBtn.setText("Save");
        saveBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Section View");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 250, 250)));

        enterVolValue.setBackground(new java.awt.Color(102, 102, 102));
        enterVolValue.setForeground(new java.awt.Color(102, 255, 255));

        enterBtn.setBackground(new java.awt.Color(0, 0, 0));
        enterBtn.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        enterBtn.setForeground(new java.awt.Color(102, 255, 255));
        enterBtn.setText("Enter");
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });

        volSlider.setBackground(new java.awt.Color(255, 255, 255));
        volSlider.setForeground(new java.awt.Color(102, 255, 255));
        volSlider.setMajorTickSpacing(20);
        volSlider.setMinorTickSpacing(5);
        volSlider.setPaintLabels(true);
        volSlider.setPaintTicks(true);
        volSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volSliderStateChanged(evt);
            }
        });

        cKey.setBackground(new java.awt.Color(255, 255, 255));
        cKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        cKey.setText("C");
        cKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKeyActionPerformed(evt);
            }
        });
        cKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cKeyKeyPressed(evt);
            }
        });

        dKey.setBackground(new java.awt.Color(255, 255, 255));
        dKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        dKey.setText("D");
        dKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKeyActionPerformed(evt);
            }
        });
        dKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dKeyKeyPressed(evt);
            }
        });

        eKey.setBackground(new java.awt.Color(255, 255, 255));
        eKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        eKey.setText("E");
        eKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        eKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKeyActionPerformed(evt);
            }
        });
        eKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eKeyKeyPressed(evt);
            }
        });

        fKey.setBackground(new java.awt.Color(255, 255, 255));
        fKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        fKey.setText("F");
        fKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fKeyActionPerformed(evt);
            }
        });
        fKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKeyKeyPressed(evt);
            }
        });

        gKey.setBackground(new java.awt.Color(255, 255, 255));
        gKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        gKey.setText("G");
        gKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gKeyActionPerformed(evt);
            }
        });
        gKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gKeyKeyPressed(evt);
            }
        });

        aKey.setBackground(new java.awt.Color(255, 255, 255));
        aKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        aKey.setText("A");
        aKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aKeyActionPerformed(evt);
            }
        });
        aKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyKeyPressed(evt);
            }
        });

        cSharp.setBackground(new java.awt.Color(0, 0, 0));
        cSharp.setForeground(new java.awt.Color(255, 255, 255));
        cSharp.setText("C#");
        cSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSharpActionPerformed(evt);
            }
        });
        cSharp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cSharpKeyPressed(evt);
            }
        });

        dSharp.setBackground(new java.awt.Color(0, 0, 0));
        dSharp.setForeground(new java.awt.Color(255, 255, 255));
        dSharp.setText("D#");
        dSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSharpActionPerformed(evt);
            }
        });
        dSharp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dSharpKeyPressed(evt);
            }
        });

        fSharp.setBackground(new java.awt.Color(0, 0, 0));
        fSharp.setForeground(new java.awt.Color(255, 255, 255));
        fSharp.setText("F#");
        fSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSharpActionPerformed(evt);
            }
        });
        fSharp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fSharpKeyPressed(evt);
            }
        });

        gSharp.setBackground(new java.awt.Color(0, 0, 0));
        gSharp.setForeground(new java.awt.Color(255, 255, 255));
        gSharp.setText("G#");
        gSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSharpActionPerformed(evt);
            }
        });
        gSharp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gSharpKeyPressed(evt);
            }
        });

        bKey.setBackground(new java.awt.Color(255, 255, 255));
        bKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        bKey.setText("B");
        bKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeyActionPerformed(evt);
            }
        });
        bKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bKeyKeyPressed(evt);
            }
        });

        highCKey.setBackground(new java.awt.Color(255, 255, 255));
        highCKey.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        highCKey.setText("C6");
        highCKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highCKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highCKeyActionPerformed(evt);
            }
        });
        highCKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                highCKeyKeyPressed(evt);
            }
        });

        aSharp.setBackground(new java.awt.Color(0, 0, 0));
        aSharp.setForeground(new java.awt.Color(255, 255, 255));
        aSharp.setText("A#");
        aSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSharpActionPerformed(evt);
            }
        });
        aSharp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aSharpKeyPressed(evt);
            }
        });

        stopBtn.setBackground(new java.awt.Color(102, 102, 102));
        stopBtn.setForeground(new java.awt.Color(102, 255, 255));
        stopBtn.setText("restart");
        stopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopBtnMouseClicked(evt);
            }
        });

        repeatBtn.setBackground(new java.awt.Color(102, 102, 102));
        repeatBtn.setForeground(new java.awt.Color(102, 255, 255));
        repeatBtn.setText("loop");
        repeatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repeatBtnMouseClicked(evt);
            }
        });

        pauseBtn.setBackground(new java.awt.Color(102, 102, 102));
        pauseBtn.setForeground(new java.awt.Color(102, 255, 255));
        pauseBtn.setText("pause");
        pauseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pauseBtnMouseClicked(evt);
            }
        });

        playBtn.setBackground(new java.awt.Color(102, 102, 102));
        playBtn.setForeground(new java.awt.Color(102, 255, 255));
        playBtn.setText("play");
        playBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playBtnMouseClicked(evt);
            }
        });

        muteBtn.setBackground(new java.awt.Color(102, 102, 102));
        muteBtn.setForeground(new java.awt.Color(102, 255, 255));
        muteBtn.setText("mute");
        muteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muteBtnMouseClicked(evt);
            }
        });

        volumeDownBtn.setBackground(new java.awt.Color(102, 102, 102));
        volumeDownBtn.setForeground(new java.awt.Color(102, 255, 255));
        volumeDownBtn.setText("volume down");
        volumeDownBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumeDownBtnMouseClicked(evt);
            }
        });

        volumeUpBtn.setBackground(new java.awt.Color(102, 102, 102));
        volumeUpBtn.setForeground(new java.awt.Color(102, 255, 255));
        volumeUpBtn.setText("volume up");
        volumeUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumeUpBtnMouseClicked(evt);
            }
        });

        GuitarText.setColumns(20);
        GuitarText.setRows(5);
        jScrollPane2.setViewportView(GuitarText);

        PianoText.setColumns(20);
        PianoText.setRows(5);
        jScrollPane3.setViewportView(PianoText);

        ViolinText.setColumns(20);
        ViolinText.setRows(5);
        jScrollPane4.setViewportView(ViolinText);

        BanjoText.setColumns(20);
        BanjoText.setRows(5);
        jScrollPane5.setViewportView(BanjoText);

        guitarButton.setLabel("guitarButton");
        guitarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guitarButtonActionPerformed(evt);
            }
        });

        pianoButton.setText("pianoButton");

        violinButton.setText("viloinButton");
        violinButton.setActionCommand("violinButton");

        banjoButton.setText("banjoButton");

        recordButton.setText("Record");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(volSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterVolValue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219)
                .addComponent(stopBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeatBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pauseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(muteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeDownBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeUpBtn)
                .addGap(185, 185, 185))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notePiano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noteViolin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(banjoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1561, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5))
                                .addGap(114, 114, 114)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(controlPanelLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(noteGuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(noteBanjo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(controlPanelLayout.createSequentialGroup()
                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(violinButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pianoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(guitarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1561, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                                .addComponent(cKey, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSharp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dKey, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dSharp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eKey, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fKey, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fSharp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gKey, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gSharp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aKey, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aSharp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bKey, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(highCKey, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(loadBtn))
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(guitarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(noteBanjo, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noteGuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(pianoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(violinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(banjoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noteViolin, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notePiano, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enterVolValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stopBtn)
                                .addComponent(repeatBtn)
                                .addComponent(pauseBtn)
                                .addComponent(playBtn)
                                .addComponent(muteBtn)
                                .addComponent(volumeDownBtn)
                                .addComponent(volumeUpBtn)
                                .addComponent(recordButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cSharp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dSharp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fSharp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gSharp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aSharp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(highCKey, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3965, 3965, 3965))
        );

        jPanel1.add(controlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1920, 1050));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     private String checkInstrument() {
         if (guitarButton.isSelected() == true)
             return "Guitar";
         else if (violinButton.isSelected() == true)
             return "Violin";
         else if (banjoButton.isSelected() == true)
             return "Banjo";
         else
             return "Piano";
               
     }
            
    private void apptitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptitleMousePressed
        // TODO add your handling code here:
        xM = evt.getX();
        yM = evt.getY();
    }//GEN-LAST:event_apptitleMousePressed

    private void apptitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptitleMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xM, y - yM);
    }//GEN-LAST:event_apptitleMouseDragged

    private void quitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quitBtnMouseClicked

    private void settingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingBtnMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Settings dialog will display here");
    }//GEN-LAST:event_settingBtnMouseClicked

    private void apptitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptitleMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            if (windowCollasped == false) {
                windowCollasped = true;
                this.setSize(new Dimension(this.getSize().width, 50));
                
                apptitle.setFont(new Font(".AppleSystemUIFont", 0, 12));
                apptitle.setText("Playing...  " + songFile.getName());
            } else if (windowCollasped == true) {
                windowCollasped = false;
                this.setSize(new Dimension(this.getSize().width, 250));
                
                apptitle.setFont(new Font(".AppleSystemUIFont", 0, 10));
                apptitle.setText(applicationName);
            }
        }
    }//GEN-LAST:event_apptitleMouseClicked

    private void volumeUpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeUpBtnMouseClicked
        // TODO add your handling code here:
        volumeupControl(0.1);
    }//GEN-LAST:event_volumeUpBtnMouseClicked

    private void volumeDownBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeDownBtnMouseClicked
        // TODO add your handling code here:
        volumedownControl(0.1);
    }//GEN-LAST:event_volumeDownBtnMouseClicked

    private void muteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muteBtnMouseClicked
        // TODO add your handling code here:
        volumeControl(0.0);
    }//GEN-LAST:event_muteBtnMouseClicked

    private void playBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseClicked
        // TODO add your handling code here:
        user.play();
    }//GEN-LAST:event_playBtnMouseClicked

    private void pauseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseBtnMouseClicked
        // TODO add your handling code here:
        user.pause();
    }//GEN-LAST:event_pauseBtnMouseClicked

    private void repeatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repeatBtnMouseClicked
        // TODO add your handling code here:
        if (repeat == false) {
            repeat = true;
            user.setRepeat(repeat);

            String image = currentPath + imagePath;
            repeatBtn.setIcon(new ImageIcon(image));
        }
        else if (repeat == true) {
            repeat = false;
            user.setRepeat(repeat);

            String image = currentPath + imagePath;
            repeatBtn.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_repeatBtnMouseClicked

    private void stopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseClicked
        // TODO add your handling code here:
        user.stop();
    }//GEN-LAST:event_stopBtnMouseClicked

    private void aSharpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aSharpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_5) {
            if(evt.getSource()==aSharp) {
               // player.play("A#");
            }
        }
    }//GEN-LAST:event_aSharpKeyPressed

    private void aSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSharpActionPerformed
        // TODO add your handling code here:
        String note = "A# ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== aSharp) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "A#");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "A#");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "A#");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "A#");            
                }      
            else
                player.play("I[" + instrument + "] " + "A#");
        }
    }//GEN-LAST:event_aSharpActionPerformed

    private void highCKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_highCKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_6) {
            if(evt.getSource()==highCKey) {
                player.play("C6");
            }
        }
    }//GEN-LAST:event_highCKeyKeyPressed

    private void highCKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highCKeyActionPerformed
        // TODO add your handling code here:
      String note = "C6 ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== highCKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "C6");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "C6");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "C6");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "C6");            
                }      
            else
                player.play("I[" + instrument + "] " + "C6");
        }
    }//GEN-LAST:event_highCKeyActionPerformed

    private void bKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_B) {
            if(evt.getSource()==bKey) {
                player.play("B");
            }
        }
    }//GEN-LAST:event_bKeyKeyPressed

    private void bKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeyActionPerformed
        // TODO add your handling code here:
       String note = "B ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== bKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "B");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "B");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "B");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "B");            
                }      
            else
                player.play("I[" + instrument + "] " + "B");
        }
    }//GEN-LAST:event_bKeyActionPerformed

    private void gSharpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gSharpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_3) {
            if(evt.getSource()==gSharp) {
                player.play("G#");
            }
        }
    }//GEN-LAST:event_gSharpKeyPressed

    private void gSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSharpActionPerformed
   String note = "G# ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== gSharp) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "G#");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "G#");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "G#");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "G#");            
                }      
            else
                player.play("I[" + instrument + "] " + "G#");
        }
    }//GEN-LAST:event_gSharpActionPerformed

    private void fSharpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSharpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_3) {
            if(evt.getSource()==fSharp) {
                player.play("F#");
            }
        }
    }//GEN-LAST:event_fSharpKeyPressed

    private void fSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSharpActionPerformed
        // TODO add your handling code here:
       String note = "F# ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== fSharp) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "F#");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "F#");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "F#");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "F#");            
                }      
            else
                player.play("I[" + instrument + "] " + "F#");
        }
    }//GEN-LAST:event_fSharpActionPerformed

    private void dSharpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dSharpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_2) {
            if(evt.getSource()==dSharp) {
                player.play("D#");
            }
        }
    }//GEN-LAST:event_dSharpKeyPressed

    private void dSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSharpActionPerformed
        // TODO add your handling code here:
         String note = "D# ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== dSharp) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "D#");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "D#");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "D#");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "D#");            
                }      
            else
                player.play("I[" + instrument + "] " + "D#");
        }
    }//GEN-LAST:event_dSharpActionPerformed

    private void cSharpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cSharpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_1) {
            if(evt.getSource()==cSharp)
            player.play("C#");
        }
    }//GEN-LAST:event_cSharpKeyPressed

    private void cSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSharpActionPerformed
        // TODO add your handling code here:
     String note = "C# ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== cSharp) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "C#");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "C#");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "C#");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "C#");            
                }      
            else
                player.play("I[" + instrument + "] " + "C#");
        }
    }//GEN-LAST:event_cSharpActionPerformed

    private void aKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_A) {
            if(evt.getSource()==aKey) {
                player.play("A");
            }
        }
    }//GEN-LAST:event_aKeyKeyPressed

    private void aKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aKeyActionPerformed
        String note = "A ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== aKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "A");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "A");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "A");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "A");            
                }      
            else
                player.play("I[" + instrument + "] " + "A");
        }
    }//GEN-LAST:event_aKeyActionPerformed

    private void gKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_G) {
            if(evt.getSource()==gKey) {
                player.play("G");
            }
        }
    }//GEN-LAST:event_gKeyKeyPressed

    private void gKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gKeyActionPerformed
         String note = "G ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== gKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "G");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "G");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "G");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "G");            
                }      
            else
                player.play("I[" + instrument + "] " + "G");
        }
    }//GEN-LAST:event_gKeyActionPerformed

    private void fKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_F) {
            if(evt.getSource()==fKey) {
                player.play("F");
            }
        }
    }//GEN-LAST:event_fKeyKeyPressed

    private void fKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fKeyActionPerformed
        String note = "F ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== fKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "F");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "F");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "F");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "F");            
                }      
            else
                player.play("I[" + instrument + "] " + "F");
        }
    }//GEN-LAST:event_fKeyActionPerformed

    private void eKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_E) {
            if(evt.getSource()==eKey) {
                player.play("E");
            }
        }
    }//GEN-LAST:event_eKeyKeyPressed

    private void eKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKeyActionPerformed
        String note = "E ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== eKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "E");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "E");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "E");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "E");            
                }      
            else
                player.play("I[" + instrument + "] " + "E");
        }
    }//GEN-LAST:event_eKeyActionPerformed

    private void dKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_D) {
            if(evt.getSource()==dKey)
            player.play("Dh");
        }
    }//GEN-LAST:event_dKeyKeyPressed

    private void dKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKeyActionPerformed
       String note = "D ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== dKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "D");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "D");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "D");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "D");            
                }      
            else
                player.play("I[" + instrument + "] " + "D");
        }
    }//GEN-LAST:event_dKeyActionPerformed
    private void cKeyActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String note = "C ";
        String instrument = checkInstrument();  
        boolean record = recordButton.isSelected();
        
        if(evt.getSource()== cKey) {
            
            if(record == true && pianoButton.isSelected ()== true)
                {               
                    PianoText.append(note); 
                    player.play("I[" + instrument + "] " + "C");            
                }
            else if (record == true && guitarButton.isSelected ()== true)
                {               
                    GuitarText.append(note); 
                    player.play("I[" + instrument + "] " + "C");            
                }
            else if (record == true && violinButton.isSelected ()== true)
                {               
                    ViolinText.append(note); 
                    player.play("I[" + instrument + "] " + "C");            
                }
            else if (record == true && banjoButton.isSelected ()== true)
                {               
                    BanjoText.append(note); 
                    player.play("I[" + instrument + "] " + "C");            
                }      
            else
                player.play("I[" + instrument + "] " + "C");
        }
    }
        
    private void cKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_C) {
            if(evt.getSource()==cKey)
            player.play("Ch");
        }
    }//GEN-LAST:event_cKeyKeyPressed

//GEN-FIRST:event_cKeyActionPerformed
 
//GEN-LAST:event_cKeyActionPerformed

    private void volSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volSliderStateChanged
        // TODO add your handling code here:
        // volSlider.validate(volumeControl());
    }//GEN-LAST:event_volSliderStateChanged

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(enterVolValue.getText());
        volSlider.setValue(value);
    }//GEN-LAST:event_enterBtnActionPerformed

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        // JFileChooser to browse File or save File
        JFileChooser saveFile = new JFileChooser("home.user");
        // set JFileChooser Title
        saveFile.setDialogTitle("Save file!");
        // set JFileChooser Filter From our newly created class
        saveFile.setFileFilter(new fileFilter(".mp3", "MP3 File Only"));
        // set JFileChooser Filter From our newly created class
        saveFile.setFileFilter(new fileFilter(" .txt", "Text File Only"));
        // store result in to INT
        int result = saveFile.showSaveDialog(null);
        // check if result returns APPROVED
        if (result == JFileChooser.APPROVE_OPTION) {
            // store text content into string
            String fileContent = songNameDisplay.getText();
            // get selected file
            File fileToSave;
            fileToSave = saveFile.getSelectedFile();
            // Now use exception to store File
            try{
                // write file writer to write that text into file
                FileWriter fileWriter = new FileWriter(fileToSave.getPath());
                // now flush the cache file
                fileWriter.flush();
                // and close FileWriter
                fileWriter.close();
            }catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "File Error: " + exception.getMessage());
            }
        }
    }//GEN-LAST:event_saveBtnMouseClicked

    private void loadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadBtnMouseClicked
        // TODO add your handling code here:
        JFileChooser loadFile = new JFileChooser(currentDirectory);
        loadFile.setDialogTitle("Load");
        // set JFileChooser Filter From our newly created class
        loadFile.setFileFilter(new fileFilter(".mp3", "MP3 file type"));
        // set JFileChooser Filter From our newly created class
        loadFile.setFileFilter(new fileFilter(".txt", "Text file type"));
        int result = loadFile.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            songFile = loadFile.getSelectedFile();
            user.addToPlayList(songFile);
            user.skipForward();
            currentDirectory = songFile.getAbsolutePath();
            songNameDisplay.setText("Playing ... " + songFile.getName());
            File selectedTextFile = loadFile.getSelectedFile();
            // read the selected file
            try{
                // using FileReader to read file
                FileReader fileReader = new FileReader(selectedTextFile);
                // buffering file
                BufferedReader bufferedReader = new BufferedReader(fileReader);
                // set buffered data into our textarea
            }catch (IOException exception) {
                JOptionPane.showMessageDialog(this, "File Open Error: " + exception.getMessage());
            }
        }
    }//GEN-LAST:event_loadBtnMouseClicked

    private void guitarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guitarButtonActionPerformed
       
    }//GEN-LAST:event_guitarButtonActionPerformed

  
       
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Set the Nimbus look and feel
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deskMusicStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deskMusicStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deskMusicStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deskMusicStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deskMusicStudio().setVisible(true);
            }
        });     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BanjoText;
    private javax.swing.JTextArea GuitarText;
    private javax.swing.JTextArea PianoText;
    private javax.swing.JLabel TrackViewName;
    private javax.swing.JTextArea ViolinText;
    private javax.swing.JButton aKey;
    private javax.swing.JButton aSharp;
    private javax.swing.JLabel apptitle;
    private javax.swing.JButton bKey;
    private javax.swing.JRadioButton banjoButton;
    private javax.swing.JButton cKey;
    private javax.swing.JButton cSharp;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton dKey;
    private javax.swing.JButton dSharp;
    private javax.swing.JButton eKey;
    private javax.swing.JButton enterBtn;
    private javax.swing.JTextField enterVolValue;
    private javax.swing.JButton fKey;
    private javax.swing.JButton fSharp;
    private javax.swing.JButton gKey;
    private javax.swing.JButton gSharp;
    private javax.swing.JRadioButton guitarButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton highCKey;
    private javax.swing.ButtonGroup instrumentButtons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel loadBtn;
    private javax.swing.JButton muteBtn;
    private javax.swing.JLabel noteBanjo;
    private javax.swing.JLabel noteGuitar;
    private javax.swing.JLabel notePiano;
    private javax.swing.JLabel noteViolin;
    private javax.swing.JButton pauseBtn;
    private javax.swing.JRadioButton pianoButton;
    private javax.swing.JButton playBtn;
    private javax.swing.JLabel quitBtn;
    private javax.swing.JToggleButton recordButton;
    private javax.swing.JButton repeatBtn;
    private javax.swing.JLabel saveBtn;
    private javax.swing.JLabel settingBtn;
    private javax.swing.JLabel songNameDisplay;
    private javax.swing.JPanel songNameMainPanel;
    private javax.swing.JPanel songNameSubPanel;
    private javax.swing.JButton stopBtn;
    private javax.swing.JRadioButton violinButton;
    public javax.swing.JSlider volSlider;
    private javax.swing.JButton volumeDownBtn;
    private javax.swing.JButton volumeUpBtn;
    // End of variables declaration//GEN-END:variables

    // custom private declaration for mp3 method
    private MP3Player mp3Player() {
        MP3Player mp3Player = new MP3Player();
        return mp3Player;
    }
    
    // custom private declaration for lowering volume
    private void volumedownControl(Double valueToPlusMinus) {
        // calling for mixer information in AudioSystem
        Mixer.Info[] mixers = AudioSystem.getMixerInfo();
        // for loop to list all mixers
        for (Mixer.Info mixerInfo : mixers) {
            // get mixer
            Mixer mixer = AudioSystem.getMixer(mixerInfo);
            // calling for target line
            Line.Info[] lineInfos = mixer.getTargetLineInfo();
            // for loop to list target lines
            for (Line.Info lineInfo : lineInfos) {
                // starts at index
                Line line = null;
                boolean opened = true;
               // try-catch method
               try {
                   line = mixer.getLine(lineInfo);
                   opened = line.isOpen() || line instanceof Clip;
                   // if statement
                   if (!opened) {
                       line.open(); // void
                   }
                   // float variable for volume control
                   FloatControl volumeControl = (FloatControl) line.getControl(FloatControl.Type.VOLUME);
                   // current volume control
                   float currentVolume = volumeControl.getValue();
                   // double variable to store valuePlusMinus
                   Double volumeToCut = valueToPlusMinus;
                   // float variable to determine volume level increase or decrease
                   float changedCalc = (float) ((float)currentVolume - (double)volumeToCut);
                   volumeControl.setValue(changedCalc);
               } catch (LineUnavailableException lineException) {
               
               } catch (IllegalArgumentException illException) {
               
               } finally {
                   // close line if it is open
                   if (line != null && !opened) {
                       line.close();
                   }
               }
            }
        }
    }
    // custom private declaration for increasing volume
    private void volumeupControl(Double valueToPlusMinus) {
        // calling for mixer information in AudioSystem
        Mixer.Info[] mixers = AudioSystem.getMixerInfo();
        // for loop to list all mixers
        for (Mixer.Info mixerInfo : mixers) {
            // get mixer
            Mixer mixer = AudioSystem.getMixer(mixerInfo);
            // calling for target line
            Line.Info[] lineInfos = mixer.getTargetLineInfo();
            // for loop to list target lines
            for (Line.Info lineInfo : lineInfos) {
                // starts at index
                Line line = null;
                boolean opened = true;
               // try-catch method
               try {
                   line = mixer.getLine(lineInfo);
                   opened = line.isOpen() || line instanceof Clip;
                   // if statement
                   if (!opened) {
                       line.open(); // void
                   }
                   // float variable for volume control
                   FloatControl volumeControl = (FloatControl) line.getControl(FloatControl.Type.VOLUME);
                   // current volume control
                   float currentVolume = volumeControl.getValue();
                   // double variable to store valuePlusMinus
                   Double volumeToCut = valueToPlusMinus;
                   // float variable to determine volume level increase or decrease
                   float changedCalc = (float) ((float)currentVolume + (double)volumeToCut);
                   volumeControl.setValue(changedCalc);
               } catch (LineUnavailableException lineException) {
               
               } catch (IllegalArgumentException illException) {
               
               } finally {
                   // close line if it is open
                   if (line != null && !opened) {
                       line.close();
                   }
               }
                
            }
        }
    }
    // custom private declaration volume in general
    public void volumeControl(Double valueToPlusMinus) {
        // calling for mixer information in AudioSystem
        Mixer.Info[] mixers = AudioSystem.getMixerInfo();
        // for loop to list all mixers
        for (Mixer.Info mixerInfo : mixers) {
            // get mixer
            Mixer mixer = AudioSystem.getMixer(mixerInfo);
            // calling for target line
            Line.Info[] lineInfos = mixer.getTargetLineInfo();
            // for loop to list target lines
            for (Line.Info lineInfo : lineInfos) {
                // starts at index
                Line line = null;
                boolean opened = true;
               // try-catch method
               try {
                   line = mixer.getLine(lineInfo);
                   opened = line.isOpen() || line instanceof Clip;
                   // if statement
                   if (!opened) {
                       line.open(); // void
                   }
                   // float variable for volume control
                   FloatControl volumeControl = (FloatControl) line.getControl(FloatControl.Type.VOLUME);
                   // current volume control
                   float currentVolume = volumeControl.getValue();
                   // double variable to store valuePlusMinus
                   Double volumeToCut = valueToPlusMinus;
                   // float variable to determine volume level increase or decrease
                   float changedCalc = (float) ((double)volumeToCut);
                   volumeControl.setValue(changedCalc);
               } catch (LineUnavailableException lineException) {
               
               } catch (IllegalArgumentException illException) {
               
               } finally {
                   // close line if it is open
                   if (line != null && !opened) {
                       line.close();
                   }
               }
                
            }
        }
    }
}
